Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'auto_apolo/negacion_empirica/Code/Fixed/requirements.R': No such file or directory
Execution halted
